import Link from 'next/link';
import clsx from 'clsx';
import { Fragment } from 'react';
import type { RichSegment } from '@/lib/content/rich-text';

/**
 * Renders pre-processed inline content.
 *
 * Deliberately imports **no maths library**: the LaTeX was already turned into
 * HTML on the server by `lib/content/rich-text.ts`. That is what keeps KaTeX
 * out of the client bundle even though quizzes and practice problems are
 * interactive client components.
 */
export function Rich({ segments, className }: { segments: RichSegment[]; className?: string }) {
  return (
    <span className={className}>
      {segments.map((s, i) => {
        switch (s.t) {
          case 'text':
            return <Fragment key={i}>{s.v}</Fragment>;
          case 'b':
            return (
              <strong key={i} className="font-semibold text-[var(--text)]">
                {s.v}
              </strong>
            );
          case 'i':
            return <em key={i}>{s.v}</em>;
          case 'code':
            return (
              <code
                key={i}
                className="rounded-[6px] bg-[var(--surface-3)] px-1.5 py-0.5 font-mono text-[0.88em]"
              >
                {s.v}
              </code>
            );
          case 'math':
            // Generated by KaTeX from our own content files, never user input.
            return <span key={i} dangerouslySetInnerHTML={{ __html: s.html }} />;
          case 'link': {
            const external = /^https?:\/\//.test(s.href);
            const cls =
              'font-medium text-[var(--accent-text)] underline underline-offset-2 decoration-[var(--accent-line)]';
            return external ? (
              <a key={i} href={s.href} target="_blank" rel="noopener noreferrer" className={cls}>
                {s.v}
              </a>
            ) : (
              <Link key={i} href={s.href} className={cls}>
                {s.v}
              </Link>
            );
          }
          default:
            return null;
        }
      })}
    </span>
  );
}

/** Display-mode maths that was rendered to HTML on the server. */
export function RichMathBlock({ html, className }: { html: string; className?: string }) {
  return (
    <div
      className={clsx('pie-math-block text-center', className)}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
